language: node_js
node_js:
  - lts/*
notifications:
  slack:
    secure: VPQIEvt8X8GimrnPLj8Uys42wtUdC588Tu6yLNDWH2KDqF9l7kBfhRMdpFjrFD0tVc1Fn/805OO7N1fdTE//zvcMNuM9SuSL4wu3iFhps1igGRfbi8w5it3hiAAjqoA6gECRInOyAPGHhwNe3dSDhZYP5kF+Xiye/jyON/wm+kmUCcFxkbKWpRU8PfS0iB0JQ2E4zuxTvNKdGffULjPBYx6jBMeDwhrTzh3r8l3fH+uYrVN6ksTC3KaDnNQ3JZVD08S1vd4byHGKD53VO6/mgB0vcRqs3TJd/CJ7pIdgAZrcQQO+q/qbTZXRCPVPT1B+ehFZbHKnv33h8aEKswVocf6meeNJ+XOSOUtlO13OloD1aP0fRWMfO4i5ZEajA28r/uf3q7nhztJUhfpSD0rZ94RpKm6t13JWg1R4AewHQZCe/U7drd4DBwaqStqk/tENhMdtGv/ZTQVQcrDbvzGVOFK6bv8f4rRlPp668KlO9TlE/AjpvrQFreOqYygT4da03CPh9gzYX0xsG+tMmqtrzTqHHwT/qeLuDtWs7bxU9fJtUBYGHlxtJ0yxikCwGAbuSyuaiW+m4/PEVWTAyBb7it55JjZjak+AXs1bxONA/lerGTyzY35cNoNmhkYQlQG7xIy1zoBSzQgIl0bq9PZCLhlPQ+JkgzPgf3OClMVyUC4=
